---
title: "1D vs. 2D Post-Hoc Binning"
author: "Isolde Lane Shaw"
date: "3/10/2022"
output: html_document
---

```{r setup, include=FALSE} 

knitr::opts_chunk$set(echo = TRUE)

options(digits=3) #limit number of digits displayed

```

# COMPARING 1D AND 2D POST-HOC BINNING


### Comparing proportions of classes normal and unimodal

Here we graph the proportion of forested classes that are normal and unimodal for 1D and 2D binning. 

 
```{r graph assumptions}
#get 1D bird assumptions for forested classes only
assumptionsByBird1DFor <- assumpTab1D[forestedStatus == "1"]
assumptionsByBird1DFor  <- droplevels(assumptionsByBird1DFor)
assumptionsByBird1DFor <- assumptionsByBird1DFor[order(birdSp)                                                                   ][,list(noClasses = .N,                                                               propClassesNormal = mean(normal),
                                               propClassesUnimodal = mean(unimodal),
                                               binningType = "1DBins"),                                               by = birdSp]
  assumptionsByBird1DFor

  #make into talbe with 2D assumptions
assumptionsbyBird <- rbind(assumptionsByBird1DFor,assumptionsByBird2D)  

#normality plot
   plotNormality <- ggplot(data = assumptionsbyBird, 
                                aes(fill= binningType, y= propClassesNormal, x= birdSp)) + 
    geom_bar(position = "dodge", stat = "identity") +
    ggtitle("Proportion of Classes Normal for 1D and 2D post-hoc binning by species") +
    xlab("Species")  +
    ylab("Proportion of classes normal (p < 0.05)") +
    theme_classic() + 
    scale_fill_manual(values=c('skyblue1', "springgreen4"), 
                      labels = c("1D", "2D")) +
    theme(title = element_text(size = 14),
          legend.title = element_blank(),
          legend.position= "bottom",
          axis.text.x = element_text(size = 10, angle = 45, hjust = 1), 
          axis.title = element_text(size = 12))

   plotNormality

#unimodality plot
   plotUnimodality <- ggplot(data = assumptionsbyBird, 
                                aes(fill= binningType, y= propClassesUnimodal, x= birdSp)) + 
    geom_bar(position = "dodge", stat = "identity") +
    ggtitle("Proportion of classes unimodal for 1D and 2D post-hoc binning by species") +
    xlab("Species")  +
    ylab("Proportion of classes unimodal (p < 0.05)") +
    theme_classic() + 
    scale_fill_manual(values=c('skyblue1', "springgreen4"), 
                      labels = c("1D", "2D")) +
    theme(title = element_text(size = 14),
          legend.title = element_blank(),
          legend.position= "bottom",
          axis.text.x = element_text(size = 10, angle = 45, hjust = 1), 
          axis.title = element_text(size = 12))

   plotUnimodality

```


### Paired t-test of unimodality and normality proportions


```{r paired t-test of unimodality and normality props}
 #Test if there is a difference in proportion of classes unimodal per bird using 1D vs 2D binning

assumptionsbyBirdTTestUnimodal <- cbind(assumptionsByBird1DFor[,c(1,4)], assumptionsByBird2D[,4])
 colnames(assumptionsbyBirdTTestUnimodal) <- c( "birdSp","propUnimodal1D", "propUnimodal2D")
 diffUniModal <- assumptionsbyBirdTTestUnimodal$propUnimodal1D - assumptionsbyBirdTTestUnimodal$propUnimodal2D
hist(diffUniModal,   
     col="darkblue", 
     main="Histogram of differences between 1D and 2D proportion of classes unimodal by bird",
     xlab="Difference")
assumptionsbyBird %>%
  group_by(binningType) %>%
  get_summary_stats(propClassesUnimodal, type = "mean_sd")
unimodalityTTest <- t.test(propClassesUnimodal ~ binningType, data = assumptionsbyBird, paired = TRUE)
unimodalityTTest


 #Test if there is a difference in proportion of classes normal per bird using 1D vs 2D binning
assumptionsbyBirdTTestNormal <- cbind(assumptionsByBird1DFor[,c(1,3)], assumptionsByBird2D[,3])
 colnames(assumptionsbyBirdTTestNormal) <- c( "birdSp","propNormal1D", "propNormal2D")
 diffNormal <- assumptionsbyBirdTTestNormal$propNormal1D - assumptionsbyBirdTTestNormal$propNormal2D
hist(diffNormal,   
     col="darkblue", 
     main="Histogram of differences between 1D and 2D proportion of classes unimodal by bird",
     xlab="Difference")
assumptionsbyBird %>%
  group_by(binningType) %>%
  get_summary_stats(propClassesNormal, type = "mean_sd")
normalityTTest <- t.test(propClassesNormal ~ binningType, data = assumptionsbyBird, paired = TRUE)
normalityTTest
```




